### PR TITLE
Fix a compatibility issue introduced in Sphinx 7.2.0 and later that changes path handling to Pathlib

### LINKED ISSUE #137: Broken since Sphinx 7.2.2
We noticed that Sphinx have deprecated old os.path lib and moved over to new Path lib since version 7.2.2 in the following commit 
 https://github.com/sphinx-doc/sphinx/commit/49d830467098cc149390bc8349c19b7501e0920f in the following MR https://github.com/sphinx-doc/sphinx/pull/11526 that caused a breaking change that cause the latest release of this lib to break down

Due to this change that the variable `app.outdir` is now a `PosixPath` instead of a str. This cause the following line of code https://github.com/bashtage/sphinx-material/blob/ac7444216f4d2a568ff9d7cfe386929537f7344d/sphinx_material/__init__.py#L74 to break down as it can't join `PosixPath + str`. The exception we get is `TypeError: unsupported operand type(s) for +: 'PosixPath' and 'str'` but the stacktrace is not existing in sphinx errors.

We will fork this and submit a PR and use our fork for now until this can be released with a fix

### PR DESCRIPTION
**Pull request by Grokzen**
Fixes #137

### CODE REVIEW

**Comment by bashtage** [comment]
TGTM.  Will commit after the run and do a quick release.

**Comment by bashtage** [comment]
Thanks.  There was another bug in the site docs that needed to be fixed to get the CI to run.

**Comment by Grokzen** [comment]
@bashtage Perfect, thank you for the quick fix/release :)

**Comment by Grokzen** [comment]
@bashtage I must caution a little tho. We only struck this error, and my PR only solved the issue we faced. I can't say for sure as we have not looked through the entire code base for all uses of this changed variable or the other ones that they changed out in the PR from sphinx. There might be more issues that we did not reached yet.

**Pull request merged**
