### PR TITLE
Update application.css

### PR DESCRIPTION
**Pull request by Anmol2001**
fixed the issue #71   of table alignment by center aligning the list table by making necessary changes in the stylesheet.
nen

### CODE REVIEW

**Comment by bashtage** [comment]
I tried this fix locally and didn't see any effect?  I;m happy to accept if ti closes this issue.  I've added a couple of demo tables to the main site with `:align:`.  Could you verify that this fix changes things with a couple of screenshots ((you will need to rebase on master to get the new tables).

Thanks.

**Comment by Anmol2001** [comment]
@bashtage  can i check on demonstration site under specimen page?

**Comment by bashtage** [comment]
I added the demo to additional specimen.

**Comment by Anmol2001** [comment]
Now,I have also removed the {display: inline block;} attribute from the small tables
 `.md-typeset .md-typeset__table` and observed the following change. 
If u think this makes sense please add label of "hacktoberfest-accepted" to this pull request.
image

**Comment by bashtage** [comment]
Sadly this fix doesn't get the job done.

**Pull request closed without merging**
