### PR TITLE
Version dropdown

### PR DESCRIPTION
**Pull request by thequackdaddy**
If interested, working on a way to bring the "other versions" to the new site.

### CODE REVIEW

**Comment by thequackdaddy** [comment]
Here's an example of this working 

https://thequackdaddy.github.io/statsmodels.github.io/devel/index.html

**Comment by thequackdaddy** [comment]
I should add you need to add `version_dropdown` to `html_theme_options`. e.g.,

```
html_theme_options = {
    'base_url': base_url,
    'repo_url': 'https://github.com/statsmodels/statsmodels',
    'repo_name': 'statsmodels',
    'globaltoc_depth': 3,
    'globaltoc_collapse': True,
    'globaltoc_includehidden': True,
    'color_primary': 'indigo',
    'color_accent': 'blue',
    'nav_title': 'statsmodels {0}'.format(version),
    'master_doc': False,
    'nav_links': [],
    'version_dropdown': True,
    'heroes': {'index': 'statistical models, hypothesis tests, and data '
                        'exploration',
               'examples/index': 'examples and tutorials to get started with '
                                 'statsmodels'}
}
```

**Comment by bashtage** [comment]
I like it.  It would be good it is also had an option version_dropdown_text which is customizable, with the default what you have.

**Comment by bashtage** [comment]
If it is enabled and there is no json file found, can it hide itself?

**Comment by thequackdaddy** [comment]
> If it is enabled and there is no json file found, can it hide itself?

By default, it already sort of does that. The javascript crashes and the html is not updated. I can read about how to do javascript (honestly quite clueless to most of it) to have it fail nicely.

**Comment by bashtage** [comment]
Would be good to not crash usually.

**Comment by thequackdaddy** [comment]
Ok... error handling makes it so you'll see this if it can't load the versions file...

image

Options can be configured as follows:

```
html_theme_options = {
    'base_url': base_url,
    'repo_url': 'https://github.com/statsmodels/statsmodels',
    'repo_name': 'statsmodels',
    'globaltoc_depth': 3,
    'globaltoc_collapse': True,
    'globaltoc_includehidden': True,
    'color_primary': 'indigo',
    'color_accent': 'blue',
    'nav_title': 'statsmodels {0}'.format(version),
    'master_doc': False,
    'nav_links': [],
    'version_dropdown': True,
    'version_dropdown_text': 'Other Versions',
    'heroes': {'index': 'statistical models, hypothesis tests, and data '
                        'exploration',
               'examples/index': 'examples and tutorials to get started with '
                                 'statsmodels'}
}
```

My example site above shows this on a limited build of the site.

**Comment by bashtage** [comment]
Thanks.

**Comment by bashtage** [comment]
I switched versions from a list to a dict, which isn't creat for sm but adds a lot of flex. I also made the location configurable so that the json can be easily shipped as part of the docs, rather than needing a manual upload (e.g., _static/versions.json). This will allow a new one in statsmodels in addition to the old one (which is annoying, but I think required).

**Pull request merged**
