### PR TITLE
ENH: Image alignment

### LINKED ISSUE #64: Images not aligned to center when :align: center is specified
If I create some RST like:

```
.. image:: ../my_image.png
  :align: center
  :scale: 60%
```

I noticed that unlike vanilla Sphinx the image is not aligned to the center of the page, and is still right justified instead.

- [reference to docs about `.. image::`](https://docutils.sourceforge.io/docs/ref/rst/directives.html#images)

### PR DESCRIPTION
**Pull request by bashtage**
closes #64

### CODE REVIEW

**Comment by johnthagen** [comment]
@bashtage Thanks for this! ❤️  Would it be possible to get a new release that includes this fix published to PyPI?

**Comment by bashtage** [comment]
Should be up on PyPI now. Thanks for the reminder.

**Comment by johnthagen** [comment]
Thanks. It looks like the wheel is missing for 0.32. Could it be uploaded?

https://pypi.org/project/sphinx-material/0.0.32/#files

My instructions for building and uploading wheels is here if you need them: https://github.com/johnthagen/python-blueprint#packaging

**Comment by bashtage** [comment]
There now.

**Pull request merged**
