### PR TITLE
Move footer out of content so it can be extended properly

### PR DESCRIPTION
**Pull request by infinity0**
If we wrap the exsting `<footer>` inside <context> in a {%- block footer %} and
then extend this, it will be represented twice in the final rendered document.
This is because in the original basic/layout.html, {%- block footer %} is
defined outside of {%- block content %}. So when the content-block is rendered
it will pull in sphinx-material's content-block (containing the footer-block)
and then later the footer-block will be rendered again.

To avoid this, this commit pulls the footer-block out of the content-block,
matching the structure of the parent template basic/layout.html. This does
depart from how mkdocs-material does things, however I believe that this is
also a bug on their end, as their `<header>` is defined outside of content but
their `<footer>` is defined inside of content, which is a strange inconsistency.

The new behaviour doesn't seem to have any adverse effects, such as CSS rules
or anything else depending on footer being inside content previously.

### CODE REVIEW

**Comment by infinity0** [comment]
Doing a diff that ignores whitespace make this PR easier to review: https://github.com/bashtage/sphinx-material/pull/10/files?w=1

I also added an extrafooter block for easier extension (e.g. to add the "social links" that mkdocs-material supports) and fixed a missing `</div>`.

**Comment by infinity0** [comment]
Correction, the `</div>` was not missing but placed in a funny location, I'm moved it to a more intuitive place.

**Comment by bashtage** [comment]
LGTM.  Have to see how it renders.

**Comment by infinity0** [comment]
Thanks! Would you be able to soon upload a release to PyPI?

**Comment by bashtage** [comment]
There is a new issue at least for some sphinx that you can see on teh devel page

https://bashtage.github.io/sphinx-material/devel/

Look at the left bar.

I'll need to fix this somehow (and figure out where it si coming from)

**Comment by bashtage** [comment]
Checked and it is ok.  On PyPI now.

**Pull request merged**
